
POST http://localhost:3003/signup
Content-Type: application/json

{  
   "name": "Roberto",
   "email": "Roberto@email.com" ,
   "password": "iSatepeter",
   "role": "ADMIN"
}

###
GET http://localhost:3003/user?email=Larissa@matos.com
Content-Type: application/json
###
POST http://localhost:3003/login
Content-Type: application/json

{
   "email": "Bruna2@email.com" ,
   "password": "iSatepeter"
}
###
GET http://localhost:3003/user/profile 
Content-Type: application/json 
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJkM2M3NTEwLTY2OTktNDM2OS04MmVhLTAxMGU1YTM4MDJiOCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NDU5MzEwMjgsImV4cCI6MTY0NTkzNDYyOH0.I4g_EmnNPGe8fjZ7LxVZHNEzFpW_QxRBo857_29wG8g